In [2]:
import tensorflow as tf
tf.set_random_seed(777)

In [3]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

In [5]:
# placeholders for a tensor what will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1], name='weight1'))
w2 = tf.Variable(tf.random_normal([1], name='weight2'))
w3 = tf.Variable(tf.random_normal([1], name='weight3'))
b = tf.Variable(tf.random_normal([1], name='bias'))
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

In [8]:
# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [10]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variable in the graph
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  8935.937 
Prediction:
 [70.81859  81.668625 82.52838  88.76229  61.929752]
10 Cost:  5.656308 
Prediction:
 [154.40627 182.1517  181.52725 196.57054 138.57646]
20 Cost:  5.545729 
Prediction:
 [154.65024 182.46185 181.82408 196.89473 138.81647]
30 Cost:  5.517083 
Prediction:
 [154.64207 182.4689  181.82227 196.89368 138.82524]
40 Cost:  5.488579 
Prediction:
 [154.63316 182.47502 181.81955 196.89166 138.8333 ]
50 Cost:  5.4602804 
Prediction:
 [154.62431 182.4811  181.81683 196.88965 138.84134]
60 Cost:  5.4320717 
Prediction:
 [154.61545 182.48718 181.81412 196.88765 138.84935]
70 Cost:  5.4040384 
Prediction:
 [154.60663 182.49323 181.81142 196.88564 138.85736]
80 Cost:  5.376172 
Prediction:
 [154.59782 182.49928 181.80875 196.88365 138.86533]
90 Cost:  5.348427 
Prediction:
 [154.58905 182.50531 181.80606 196.88165 138.87329]
100 Cost:  5.3208437 
Prediction:
 [154.5803  182.51134 181.80339 196.87967 138.88123]
110 Cost:  5.293374 
Prediction:
 [154.57153 182.5173  181.80

1100 Cost:  3.1970458 
Prediction:
 [153.8144  183.03687 181.56932 196.70522 139.5753 ]
1110 Cost:  3.181059 
Prediction:
 [153.80774 183.04144 181.56728 196.70369 139.58134]
1120 Cost:  3.165196 
Prediction:
 [153.80112 183.04602 181.56528 196.70218 139.58737]
1130 Cost:  3.1494017 
Prediction:
 [153.79448 183.05055 181.56323 196.70067 139.59337]
1140 Cost:  3.1337245 
Prediction:
 [153.78789 183.05507 181.56122 196.69914 139.59935]
1150 Cost:  3.1181064 
Prediction:
 [153.78131 183.0596  181.55922 196.69765 139.60533]
1160 Cost:  3.1025848 
Prediction:
 [153.77475 183.0641  181.5572  196.69615 139.61128]
1170 Cost:  3.0871344 
Prediction:
 [153.7682  183.0686  181.55524 196.69467 139.61725]
1180 Cost:  3.0717397 
Prediction:
 [153.76166 183.07309 181.55319 196.69316 139.62315]
1190 Cost:  3.056479 
Prediction:
 [153.75514 183.07755 181.55122 196.69165 139.62906]
1200 Cost:  3.0412834 
Prediction:
 [153.74864 183.082   181.54924 196.69017 139.63495]
1210 Cost:  3.026176 
Prediction:
 