In [5]:
import tensorflow as tf
import numpy as np

In [7]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [8]:
# Make sure the shape and data are OK
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25
(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [9]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loass function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [10]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [11]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
    [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost ", cost_val, "\nPrediction:\n", hy_val)

0 Cost  302.86414 
Prediction:
 [[159.61469 ]
 [209.44649 ]
 [197.19292 ]
 [216.22383 ]
 [162.87227 ]
 [124.334015]
 [159.04012 ]
 [113.46693 ]
 [201.58354 ]
 [191.48503 ]
 [156.97038 ]
 [163.0855  ]
 [202.56688 ]
 [167.48814 ]
 [162.55756 ]
 [212.29762 ]
 [163.19978 ]
 [187.73332 ]
 [190.17491 ]
 [168.50609 ]
 [188.53166 ]
 [196.76723 ]
 [177.84087 ]
 [158.10262 ]
 [213.63667 ]]
10 Cost  51.756134 
Prediction:
 [[144.85376 ]
 [191.65173 ]
 [179.68732 ]
 [197.15518 ]
 [149.29068 ]
 [114.308846]
 [144.776   ]
 [102.90719 ]
 [184.93611 ]
 [176.05243 ]
 [143.21555 ]
 [149.49792 ]
 [184.48402 ]
 [152.4577  ]
 [148.2195  ]
 [194.24152 ]
 [148.8732  ]
 [170.62506 ]
 [172.94434 ]
 [153.09393 ]
 [171.79839 ]
 [180.07317 ]
 [161.89261 ]
 [143.22705 ]
 [195.20462 ]]
20 Cost  51.46322 
Prediction:
 [[144.77913]
 [191.50879]
 [179.57423]
 [197.02827]
 [149.1715 ]
 [114.209  ]
 [144.69041]
 [102.85846]
 [184.7856 ]
 [175.90002]
 [143.12105]
 [149.3798 ]
 [184.37001]
 [152.36464]
 [148.12514]
 [194.

380 Cost  42.49861 
Prediction:
 [[145.70616 ]
 [190.82298 ]
 [179.83586 ]
 [197.1942  ]
 [148.29921 ]
 [113.17211 ]
 [145.14304 ]
 [103.706375]
 [183.58185 ]
 [174.36128 ]
 [143.14256 ]
 [148.5612  ]
 [184.72911 ]
 [152.71054 ]
 [148.29784 ]
 [193.45525 ]
 [148.6872  ]
 [171.41798 ]
 [173.48283 ]
 [153.7542  ]
 [172.00636 ]
 [179.29515 ]
 [162.28282 ]
 [144.31224 ]
 [194.69362 ]]
390 Cost  42.278687 
Prediction:
 [[145.73022]
 [190.80502]
 [179.84256]
 [197.1986 ]
 [148.27625]
 [113.14522]
 [145.15517]
 [103.72911]
 [183.55063]
 [174.32175]
 [143.14325]
 [148.54007]
 [184.73816]
 [152.71902]
 [148.30269]
 [193.4386 ]
 [148.68423]
 [171.44159]
 [173.49915]
 [153.77335]
 [172.0149 ]
 [179.27847]
 [162.29576]
 [144.34177]
 [194.6837 ]]
400 Cost  42.060226 
Prediction:
 [[145.75423]
 [190.78712]
 [179.84924]
 [197.203  ]
 [148.25337]
 [113.11845]
 [145.1673 ]
 [103.75183]
 [183.51955]
 [174.2824 ]
 [143.14397]
 [148.51904]
 [184.74718]
 [152.72745]
 [148.30757]
 [193.42201]
 [148.68124]
 

770 Cost  34.89972 
Prediction:
 [[146.5839  ]
 [190.16248 ]
 [180.07724 ]
 [197.3576  ]
 [147.45108 ]
 [112.193085]
 [145.59912 ]
 [104.5618  ]
 [182.44522 ]
 [172.93549 ]
 [143.17258 ]
 [147.79575 ]
 [185.0488  ]
 [153.00143 ]
 [148.4888  ]
 [192.84915 ]
 [148.55197 ]
 [172.30055 ]
 [174.06752 ]
 [154.44511 ]
 [172.33026 ]
 [178.68883 ]
 [162.76526 ]
 [145.37248 ]
 [194.32442 ]]
780 Cost  34.728973 
Prediction:
 [[146.60481]
 [190.14656]
 [180.0829 ]
 [197.36159]
 [147.43056]
 [112.16976]
 [145.61035]
 [104.58289]
 [182.41815]
 [172.90187]
 [143.17339]
 [147.77759]
 [185.05614]
 [153.00787]
 [148.4937 ]
 [192.8347 ]
 [148.54802]
 [172.32216]
 [174.08119]
 [154.46138]
 [172.33833]
 [178.67438]
 [162.77702]
 [145.39732]
 [194.31538]]
790 Cost  34.55927 
Prediction:
 [[146.62566 ]
 [190.13069 ]
 [180.08855 ]
 [197.36555 ]
 [147.41008 ]
 [112.14651 ]
 [145.62157 ]
 [104.603935]
 [182.39116 ]
 [172.8684  ]
 [143.17424 ]
 [147.75954 ]
 [185.06345 ]
 [153.0143  ]
 [148.4986  ]
 [192.82033 ]

1160 Cost  28.983288 
Prediction:
 [[147.34723]
 [189.57663]
 [180.2808 ]
 [197.50484]
 [146.692  ]
 [111.34299]
 [146.02068]
 [105.35402]
 [181.45808]
 [171.72229]
 [143.2069 ]
 [147.13771]
 [185.30771]
 [153.22054]
 [148.67949]
 [192.32297]
 [148.38393]
 [173.10823]
 [174.55763]
 [155.03294]
 [172.63525]
 [178.16327]
 [163.20454]
 [146.26552]
 [193.98761]]
1170 Cost  28.849964 
Prediction:
 [[147.36543 ]
 [189.5625  ]
 [180.28558 ]
 [197.50842 ]
 [146.67361 ]
 [111.32272 ]
 [146.03104 ]
 [105.373535]
 [181.43456 ]
 [171.69368 ]
 [143.20781 ]
 [147.1221  ]
 [185.31363 ]
 [153.22533 ]
 [148.68436 ]
 [192.31041 ]
 [148.37927 ]
 [173.12799 ]
 [174.56909 ]
 [155.04681 ]
 [172.64282 ]
 [178.15076 ]
 [163.21527 ]
 [146.28647 ]
 [193.97937 ]]
1180 Cost  28.717432 
Prediction:
 [[147.38359 ]
 [189.54842 ]
 [180.29033 ]
 [197.51198 ]
 [146.65529 ]
 [111.30252 ]
 [146.0414  ]
 [105.393005]
 [181.4111  ]
 [171.66518 ]
 [143.20872 ]
 [147.10655 ]
 [185.31953 ]
 [153.23009 ]
 [148.68921 ]
 [192.29

1540 Cost  24.457956 
Prediction:
 [[147.99611]
 [189.06895]
 [180.44849]
 [197.63432]
 [146.0286 ]
 [110.62152]
 [146.40007]
 [106.06825]
 [180.62013]
 [170.71367]
 [143.24303]
 [146.58485]
 [185.51164]
 [153.3781 ]
 [148.86244]
 [191.87646]
 [148.19841]
 [173.82875]
 [174.95874]
 [155.52165]
 [172.9142 ]
 [177.71803]
 [163.59465]
 [147.00014]
 [193.688  ]]
1550 Cost  24.352655 
Prediction:
 [[148.01205]
 [189.05637]
 [180.45255]
 [197.63754]
 [146.01208]
 [110.60382]
 [146.40964]
 [106.08631]
 [180.59956]
 [170.68918]
 [143.24399]
 [146.57135]
 [185.51645]
 [153.3816 ]
 [148.86719]
 [191.86552]
 [148.19333]
 [173.84686]
 [174.96838]
 [155.5335 ]
 [172.9213 ]
 [177.70712]
 [163.60445]
 [147.01785]
 [193.68048]]
1560 Cost  24.248018 
Prediction:
 [[148.02791]
 [189.04381]
 [180.45656]
 [197.64076]
 [145.99559]
 [110.58619]
 [146.4192 ]
 [106.10433]
 [180.57909]
 [170.66481]
 [143.24498]
 [146.5579 ]
 [185.52122]
 [153.38509]
 [148.87193]
 [191.8546 ]
 [148.18822]
 [173.86494]
 [174.977

1930 Cost  20.793413 
Prediction:
 [[148.57799]
 [188.60507]
 [180.59404]
 [197.75432]
 [145.41739]
 [109.9756 ]
 [146.7592 ]
 [106.74541]
 [179.86975]
 [169.8296 ]
 [143.2817 ]
 [146.09492]
 [185.68001]
 [153.49365]
 [149.04521]
 [191.47682]
 [147.99376]
 [174.50536]
 [175.30446]
 [155.94997]
 [173.18204]
 [177.32011]
 [163.95949]
 [147.63683]
 [193.40742]]
1940 Cost  20.710403 
Prediction:
 [[148.5919 ]
 [188.59387]
 [180.59744]
 [197.75723]
 [145.40257]
 [109.96018]
 [146.76802]
 [106.76205]
 [179.85184]
 [169.80875]
 [143.28268]
 [146.0833 ]
 [185.68385]
 [153.4961 ]
 [149.0498 ]
 [191.46729]
 [147.98837]
 [174.52191]
 [175.31256]
 [155.96008]
 [173.18866]
 [177.31064]
 [163.9684 ]
 [147.65176]
 [193.40056]]
1950 Cost  20.627878 
Prediction:
 [[148.60576]
 [188.5827 ]
 [180.60085]
 [197.76015]
 [145.3878 ]
 [109.94482]
 [146.77681]
 [106.77866]
 [179.83397]
 [169.78795]
 [143.28369]
 [146.0717 ]
 [185.68767]
 [153.49849]
 [149.0544 ]
 [191.45778]
 [147.98299]
 [174.53844]
 [175.320

In [12]:
# Ask my score
print("Your score will be", sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))
print("Other scores will be ", sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

Your score will be [[206.60832]]
Other scores will be  [[170.0427]
 [170.7022]]
